require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe ConventionsController do

  # This should return the minimal set of attributes required to create a valid
  # Convention. As you add validations to Convention, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    {:name=> "Name", :begin_date => "2013-04-21 12:21:17",:end_date => "2013-04-21 12:21:17"}
  end

  describe "GET index" do
    it "assigns all conventions as @conventions" do
      user = Factory(:user)
      convention = user.conventions.create! valid_attributes
      get :index
      assigns(:conventions).should eq([convention])
    end
  end

  describe "GET show" do
    it "assigns the requested convention as @convention" do
      user = Factory(:user)
      convention = user.conventions.create! valid_attributes
      get :show, :id => convention.id
      assigns(:convention).should eq(convention)
    end
  end

  describe "GET new" do
    it "assigns a new convention as @convention" do
      get :new
      assigns(:convention).should be_a_new(Convention)
    end
  end

  describe "GET edit" do
    it "assigns the requested convention as @convention" do
      user = Factory(:user)
      convention = user.conventions.create! valid_attributes
      get :edit, :id => convention.id
      assigns(:convention).should eq(convention)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Convention" do
        expect {
          post :create, :user_id => 1, :convention => valid_attributes
        }.to change(Convention, :count).by(1)
      end

      it "assigns a newly created convention as @convention" do
        post :create, :user_id => 1, :convention => valid_attributes
        assigns(:convention).should be_a(Convention)
        assigns(:convention).should be_persisted
      end

      it "redirects to the created convention" do
        post :create, :user_id => 1, :convention => valid_attributes
        response.should redirect_to(Convention.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved convention as @convention" do
        # Trigger the behavior that occurs when invalid params are submitted
        Convention.any_instance.stub(:save).and_return(false)
        post :create, :convention => {}
        assigns(:convention).should be_a_new(Convention)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Convention.any_instance.stub(:save).and_return(false)
        post :create, :convention => {}
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested convention" do
        user = Factory(:user)
        convention = user.conventions.create! valid_attributes
        # Assuming there are no other conventions in the database, this
        # specifies that the Convention created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        Convention.any_instance.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, :id => convention.id, :convention => {'these' => 'params'}
      end

      it "assigns the requested convention as @convention" do
        user = Factory(:user)
        convention = user.conventions.create! valid_attributes
        put :update, :id => convention.id, :convention => valid_attributes
        assigns(:convention).should eq(convention)
      end

      it "redirects to the convention" do
        user = Factory(:user)
        convention = user.conventions.create! valid_attributes
        put :update, :id => convention.id, :convention => valid_attributes
        response.should redirect_to(convention)
      end
    end

    describe "with invalid params" do
      it "assigns the convention as @convention" do
        user = Factory(:user)
        convention = user.conventions.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Convention.any_instance.stub(:save).and_return(false)
        put :update, :id => convention.id, :convention => {}
        assigns(:convention).should eq(convention)
      end

      it "re-renders the 'edit' template" do
        user = Factory(:user)
        convention = user.conventions.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Convention.any_instance.stub(:save).and_return(false)
        put :update, :id => convention.id, :convention => {}
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested convention" do
      user = Factory(:user)
      convention = user.conventions.create! valid_attributes
      expect {
        delete :destroy, :id => convention.id
      }.to change(Convention, :count).by(-1)
    end

    it "redirects to the conventions list" do
      user = Factory(:user)
      convention = user.conventions.create! valid_attributes
      delete :destroy, :id => convention.id
      response.should redirect_to(conventions_url)
    end
  end

end
